### ISSUE TITLE
Make links more explicit

### ISSUE THREAD

**Issue by simonwex** [mozilla/build.webmaker.org#1]
_From @davidascher on January 16, 2015 19:40_

e.g. issue titles are links.  (as simple as underline on hover would be fine)

_Copied from original issue: MozillaFoundation/plan#233_

**Comment by simonwex** [comment]
_From @thisandagain on January 16, 2015 20:0_

Major :+1: on that ... I got sloppy with hover states. :stuck_out_tongue_winking_eye:

**Comment by davidascher** [comment]
done enough for now
