### ISSUE TITLE
A favicon to help with pinned tabs 

### ISSUE THREAD

**Issue by adamlofting** [mozilla/build.webmaker.org#11]
![screen shot 2015-01-21 at 15 23 07](https://cloud.githubusercontent.com/assets/1901816/5838758/6ece0406-a181-11e4-91bb-10999486a296.png)

Would be a welcome tweak :smile:

**Comment by davidascher** [comment]
@vazquez if you're ever bored ;-)

**Comment by vazquez** [comment]
Got it :)
