### ISSUE TITLE
Transfer Heroku app to Mozilla org

### ISSUE THREAD

**Issue by simonwex** [mozilla/build.webmaker.org#18]
This can be done in the settings for the app. Looks like this:

![image](https://cloud.githubusercontent.com/assets/25260/5848779/45a7dd30-a191-11e4-90f8-cedee70f935b.png)

**Comment by davidascher** [comment]
I thought it was, I'll check.

**Comment by davidascher** [comment]
I believe @jdotpz has build.webmaker.org pointed at https://mofo-intake.herokuapp.com/ which is a mozilla-group heroku app.

**Comment by simonwex** [comment]
Ah, my bad. I didn't recognize the name.
