### ISSUE TITLE
Add design assets

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/build.webmaker.org#30]
Fonts, logos, and other perennial assets would be useful collected on this site. Maintaining a collection like that can be messy and tedious. In the short-term, can we link to or embed our fledgling items on [google drive](https://drive.google.com/folderview?id=0B_rbDAen9prkS0N4MXRqaGo4bEE&usp=sharing)? This collection should be kept minimal and avoid clutter. 

@cassiemc

**Comment by davidascher** [comment]
done.
