### ISSUE TITLE
Routing bug if linking direct to /audience

### ISSUE THREAD

**Issue by adamlofting** [mozilla/build.webmaker.org#39]
If I navigate direct to [/audience](http://build.webmaker.org/audience), I see this:
![screen shot 2015-02-09 at 09 36 13](https://cloud.githubusercontent.com/assets/1901816/6103739/2eaae6ec-b03f-11e4-87da-2ccb973d0965.png)

But it works if I get there via the nav from the homescreen.
![screen shot 2015-02-09 at 09 38 10](https://cloud.githubusercontent.com/assets/1901816/6103769/673f630c-b03f-11e4-9954-07a353c2fb2f.png)

**Comment by davidascher** [comment]
Ah, my bad. Easy to fix, although the generic problem to avoid that bug
again isn't trivial.

**Comment by davidascher** [comment]
Need to figure out how to document the architecture so that when people add
a new route, it gets added to the server.js routes, not just the clientside
routes.

(or maybe add a specific route that returns the SPA on every single-word
path)

**Comment by davidascher** [comment]
Fixed by https://github.com/mozilla/build.webmaker.org/pull/42
