### ISSUE TITLE
Setup travis again

### ISSUE THREAD

**Issue by davidascher** [mozilla/build.webmaker.org#5]
T'was working on the MozillaFoundation/plan repo, just need to copy those settings again. (Note: was also doing push-to-heroku on push-to-master).

**Comment by simonwex** [comment]
Build is now failing on deploy. Heroku API key needs to be updated. @davidascher ?

```
...
Expected(200) <=> Actual(401 Unauthorized)
body: "{\"id\":\"unauthorized\",\"error\":\"Invalid credentials provided.\"}" (wrong API key?)
failed to deploy
```

**Comment by davidascher** [comment]
Where's the heroku key set? your travis config @simonwex?

**Comment by simonwex** [comment]
I just set it up using my deploy key.
