### ISSUE TITLE
Inter-word spaces missing in build.webmaker.org home page text

### ISSUE THREAD

**Issue by ttmc** [mozilla/build.webmaker.org#61]
When I visit https://build.webmaker.org/ I get the home page, and something is wrong with the way the paragraph text is being displayed/rendered: many of the spaces between words are missing. For example, in the first sentence, "organization that" appears as "organizationthat".

To help you replicate this problem, here's what I was using:

Operating System: Mac OS X 10.10.2 (Yosemite)

Browsers: Firefox 36.0.1, Chrome 41.0.2272.76 (64-bit)

Extensions running in Firefox: ChatZilla, Disconnect, Facebook Disconnect, Google Disconnect, Twitter Disconnect

Browser extensions running in Chrome: Adblock Plus, Privacy Badger

**Comment by jbuck** [comment]
Looks like it's because it's rendering the paragraph text with multiple `<span>` elements. I wonder why it's doing that

**Comment by davidascher** [comment]
react problem.  need to end lines with a whitespace. /cc @pomax

**Comment by LucyeoH-zz** [comment]
Thanks again so much for filing this @ttmc!

**Comment by Pomax** [comment]
Sort of on the fence on this one, since it's not just jsx/beautifiers that will cause this problem, but also text editors that are set to trim trailing space, which we'll still want even in jsx files.

If a trailing space is necessary in our components, it's probably going to be solved with something that forces them in through JSX syntax, like appending a `{' '}` in the render return where they are necessary

**Comment by davidascher** [comment]
I think we should find a way to fix it upstream, but it's a mess.

Some background:
- https://github.com/facebook/jsx/issues/19
- https://github.com/facebook/react/pull/480

**Comment by ttmc** [comment]
One of the first lessons you learn in engineering is KISS: Keep It Simple, Silly! (Yes, there are variations on the last word.)

Why is a fancy new JavaScript framework needed to make a static home page? Isn't the whole idea of Webmaker that _anyone_ can make web pages, that it's not hard?

Even if you want something more sophisticated (e.g. a CMS and something to help organize the Agile stuff), this is Mozilla we're talking about. Doesn't Mozilla already have some standard CMS and project-management tools?

**Comment by davidascher** [comment]
We should take the conversation of the tooling somewhere else.  If this bug
is still present it is easy to fix (just add some end of line spaces in the
source file).
