### ISSUE TITLE
Getting Started is inaccurate

### ISSUE THREAD

**Issue by gvn** [mozilla/build.webmaker.org#64]
`cd plan` is mentioned, but there isn't a `plan` directory in the root.

**Comment by adamlofting** [comment]
- [x] I think the repo was originally called `plan`, and this should now be `cd build.webmaker.org` 
- [x] There's also no `app.js` in the root now, as mentioned in the existing docs

**Comment by adamlofting** [comment]
- [x] Update sample env location to this: `cp server/config/production.env.sample .env`

**Comment by adamlofting** [comment]
- [x] Might need to add `FIREBASE_SECRET` to env.sample and documentation (depending on #65 )
