### ISSUE TITLE
⚓️⚓️❤️❤️ My kingdom for a way to rank issues

### ISSUE THREAD

**Issue by hannahkane** [mozilla/build.webmaker.org#75]
I am regularly wanting a way to say "issue x is more important than issue y which is more important than issue z."

This would be useful both in terms of planning/loading heartbeats, and for engineers/designers to determine what to work on next _within_ a heartbeat.

**Comment by davidascher** [comment]
A thing I've used in the past is to add unicode markers to the issue
names.  Doesn't help w/ sorting inside of Github, as Github doesn't let you
sort by name, but communicating things like user value and
"small/medium/large" can be done with things like emojis (hearts for user
value, anchors for 'weight'):

```
https://github.com/davidascher/simple/issues
```

**Comment by thisandagain** [comment]
I like the emoji title idea. I use labels (critical > bug > feature > enhancement) within the active milestone to help prioritize, but it's certainly not as helpful as an ordered list.

**Comment by hannahkane** [comment]
The emoji idea is nice. How do I add emojis to titles?
Am definitely making good use of labels, too.

Thanks!

**Comment by hannahkane** [comment]
Oh, like that.

**Comment by cassiemc** [comment]
@hannahkane can we close this?

**Comment by hannahkane** [comment]
Hmm...sure. I mean, I still want a way to order github issues, but I don't think I'm going to get one. :)

**Comment by cassiemc** [comment]
@hannahkane I thought this was solved by the hack above but if not, feel free to leave it open! 

(I don't think this repo has been triaged in quite some time and I am attempting to assess how it's working for us by going through old bugs)

**Comment by hannahkane** [comment]
The hack allows us to indicate things like "user value" and "weight," as David mentioned above, but doesn't solve the original problem of wanting to literally order issues. e.g. issue x is more important than issue y. Github doesn't seem to support that, so I'll keep this closed.
