### ISSUE TITLE
Update url

### ISSUE THREAD

**Issue by cassiemc** [mozilla/build.webmaker.org#95]
URLs are no longer reflective of our terminology and scope, ie. they shouldn't be using the webmaker domain. 

What are some alternatives?

Looks like we own www.mozillafoundation.org, which autoforwards to https://www.mozilla.org/en-US/foundation/. Could we use the former domain – with build.mozillafoundation.org? cc @jbuck @simonwex  @hannahkane @OpenMatt @davidascher

**Comment by OpenMatt** [comment]
@cassiemc I just registered mofo.build -- was planning to push ahead with that and try to get it moved next week. Will present that proposal in Heartbeat planning mtg tmrw.

**Comment by cassiemc** [comment]
How did this go @OpenMatt? Wondering if anyone brought up reservations about 'mofo' as an abbreviation and its more popular meaning. @simonwex and I were discussing it earlier this week.

**Comment by OpenMatt** [comment]
I've had the same thought. But I think it's ok as a temporary home. Then we
can move things around based on the overall IA and standardization work you
and hannah have started.

**Comment by cassiemc** [comment]
:+1:
